server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    username: mysqladmin
    password: "developEnv@0417"
    host: 172.24.161.143:3306
    database: voice1017
    max_open_connections: 10
    timeout: 10s
    max_idle_connections: 10
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
config:
  encrypt_key: "jdgD46d7G7ObhwgU"
  