// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsOk(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OK.String() && e.Code == 200
}

func ErrorOk(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_OK.String(), fmt.Sprintf(format, args...))
}

// 用户名重复
func IsUsernameRepeat(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USERNAME_REPEAT.String() && e.Code == 600
}

// 用户名重复
func ErrorUsernameRepeat(format string, args ...interface{}) *errors.Error {
	return errors.New(600, ErrorReason_USERNAME_REPEAT.String(), fmt.Sprintf(format, args...))
}

// 用户名或密码错误
func IsUserOrPasswordInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_OR_PASSWORD_INVALID.String() && e.Code == 600
}

// 用户名或密码错误
func ErrorUserOrPasswordInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(600, ErrorReason_USER_OR_PASSWORD_INVALID.String(), fmt.Sprintf(format, args...))
}
